# Generated by Django 4.2.13 on 2024-07-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_service_category_remove_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.JSONField(default=list, help_text='List of features.'),
        ),
    ]
