# Generated by Django 5.0.6 on 2024-07-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_project_status_profile_is_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='static/profile_pictures/9334228.jpg', upload_to='static/profile_pictures/'),
        ),
    ]
