# Generated by Django 5.0.6 on 2024-07-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='static/profile_pictures/9334228.jpg', upload_to='static/profile_pictures/'),
        ),
    ]
