# Generated by Django 5.0.6 on 2024-07-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price_premium',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_premium_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_standard',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_standard_description',
        ),
    ]
