# Generated by Django 5.0.6 on 2024-07-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_service_price_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_projects', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='step1_file',
            field=models.FileField(blank=True, null=True, upload_to='static/project_files/step1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='step2_file',
            field=models.FileField(blank=True, null=True, upload_to='static/project_files/step2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='step3_file',
            field=models.FileField(blank=True, null=True, upload_to='static/project_files/step3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='step4_file',
            field=models.FileField(blank=True, null=True, upload_to='static/project_files/step4'),
        ),
        migrations.AlterField(
            model_name='project',
            name='step5_file',
            field=models.FileField(blank=True, null=True, upload_to='static/project_files/step5'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/order_message_files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='main.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='main.profile')),
            ],
        ),
    ]
