# Generated by Django 5.0.6 on 2024-07-12 23:42

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_project_client_alter_project_freelancer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='descriptio',
            new_name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='categorie',
            field=models.ForeignKey(default=main.models.Categorie.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='main.categorie'),
        ),
    ]
