# Generated by Django 5.0.6 on 2024-07-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_project_client_alter_project_freelancer_and_more'),
        ('main', '0013_rename_descriptio_categorie_description_and_more'),
    ]

    operations = [
    ]
